---
- name: Instalar servicio Apache
  include_tasks: install-apache2.yml

- name: Crear directorio para el sitio
  file:
    path: "{{ site_dir }}"
    state: directory
    owner: www-data
    group: www-data

- name: Copiar index.html al directorio del sitio
  copy:
    src: index.html
    dest: "{{ site_dir }}"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Configuración del sitio Apache
  template:
    src: ansible_site.conf.j2
    dest: /etc/apache2/sites-available/ansible_site.conf
  notify:
    - Reload Apache

- name: Activar el nuevo sitio
  command: a2ensite ansible_site.conf
  notify:
    - Reload Apache

- name: Deshabilitar el sitio default
  command: a2dissite 000-default.conf
  notify:
    - Reload Apache

- name: Cambiar el e-mail del webmaster
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: 'ServerAdmin webmaster@localhost'
    line: 'ServerAdmin webmaster@educacionit.com'
  notify:
    - Reload Apache
